version: '3.8'

services:
  postgres:
    container_name: gemini-back
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: gemini_todo